# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8aa950e0e8adfebde66d2be9a0c7db7c9cd22811419948c1868d7863785b2bb51f6ffd00867901695a615a61ba7d015679a5c44453aee9607215d650569656

test:
  secret_key_base: e45ecb0665948f4c8655dd5ed737b2fb68a4d8ea018c3168d937472be9f588bea80b72e755ed0bd91848a7b96e168ebcf23f23aacd20b193640fb783c9a94fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
